version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: fieldeyes-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123456
      POSTGRES_DB: field_eyes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fieldeyes-network

  # Redis Cache
  redis:
    image: redis:7
    container_name: fieldeyes-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
    networks:
      - fieldeyes-network

  # Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: fieldeyes-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - fieldeyes-network

  # Field Eyes API
  app:
    build: .
    container_name: fieldeyes-api
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "9004:9004"
    env_file:
      - .env
    networks:
      - fieldeyes-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database Admin Tool
  pgadmin:
    image: dpage/pgadmin4
    container_name: fieldeyes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fieldeyes.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fieldeyes-network
      
  # Redis Admin Tool
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: fieldeyes-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - fieldeyes-network
      
  # MQTT Dashboard
  mqtt-dashboard:
    image: eclipse-mosquitto:2
    container_name: fieldeyes-mqtt-dashboard
    restart: unless-stopped
    command: sh -c "wget -O /tmp/mqtt-dashboard.js https://raw.githubusercontent.com/hui6075/mqtt-admin-panel/master/index.html && mkdir -p /mosquitto/www && mv /tmp/mqtt-dashboard.js /mosquitto/www/index.html && mosquitto_sub -h mosquitto -t '#' -v"
    volumes:
      - ./mqtt-dashboard:/mosquitto/www
    depends_on:
      - mosquitto
    ports:
      - "9002:9001"
    networks:
      - fieldeyes-network

networks:
  fieldeyes-network:
    driver: bridge

volumes:
  pgdata:
  redis_data: 