version: '3.8'

services:
  api:
    build: .
    ports:
      - "9004:9004"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=field_eyes
      - DSN=host=postgres port=5432 user=postgres password=postgres dbname=field_eyes sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: 'postgres:14.2'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: field_eyes
    ports:
      - "5434:5432"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: 'redis:7'
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis/:/data
    networks:
      - app-network

  mqtt:
    image: 'eclipse-mosquitto:2'
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./db-data/mqtt/:/mosquitto/data
      - ./db-data/mqtt/log/:/mosquitto/log
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
