services:
  # PostgreSQL database service
  postgres:
    image: 'postgres:14.2'
    container_name: fieldeyes-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123456
      POSTGRES_DB: field_eyes
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    networks:
      - fieldeyes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis cache service
  redis:
    image: 'redis:alpine'
    container_name: fieldeyes-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data
    networks:
      - fieldeyes-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  fieldeyes-network:
    driver: bridge